version: '3.8'

services:
  postgres:
    image: postgres:14.18
    container_name: cinematec_postgres
    environment:
      POSTGRES_DB: cinematec_explorer
      POSTGRES_USER: cinematec_user
      POSTGRES_PASSWORD: cinematec_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    build: .
    container_name: cinematec_app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://cinematec_user:cinematec_password@postgres:5432/cinematec_explorer
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: